# Generated by Django 6.0.5 on 2026-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_id_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
