# Generated by Django 6.0.5 on 2026-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_notes_product_status_product_supplier_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='handled_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
