# Generated by Django 6.0.5 on 2026-05-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
