# Generated by Django 6.0.3 on 2026-05-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_business_reminder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='source_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='type',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
