# Generated by Django 6.0.4 on 2026-05-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_reminder_external_id_reminder_source_app_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='source_app',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='type',
        ),
    ]
