# Generated by Django 6.0.5 on 2026-05-07 11:54

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemalert_systemcredential_alter_systemlog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedEmail',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(default='primary', max_length=50)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='Connected', max_length=50)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('business', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
