# Generated by Django 6.0.3 on 2026-05-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_note_color_note_created_at_note_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcredential',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
