# Generated by Django 6.0.5 on 2026-05-07 05:04

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_vatrecord_alter_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoSettlement',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(default='Card', max_length=100)),
                ('status', models.CharField(default='Settled', max_length=50)),
            ],
        ),
    ]
