# Generated by Django 6.0.5 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_dojosettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='accounting/invoices/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/documents/'),
        ),
    ]
