# Generated by Django 6.0.5 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_bankaccount_status_alter_dojosettlement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/insurance/'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='renewal_reminder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/tax/'),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
