# Generated by Django 6.0.3 on 2026-05-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_invoice_invoice_date_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
