# Generated by Django 6.0.3 on 2026-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/banks/'),
        ),
    ]
