# Generated by Django 6.0.3 on 2026-05-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_bankaccount_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='accounting/loans/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
