# Generated by Django 6.0.3 on 2026-05-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_loan_document_loan_purpose_loan_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='asset_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
