# Generated by Django 6.0.3 on 2026-05-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_insurancepolicy_asset_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='asset_details',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='vatrecord',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='vatrecord',
            name='payment_due',
        ),
        migrations.RemoveField(
            model_name='vatrecord',
            name='transaction_ref',
        ),
    ]
