# Generated by Django 6.0.3 on 2026-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_insurancepolicy_asset_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='asset_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
