# Generated by Django 6.0.3 on 2026-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_insurancepolicy_asset_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatrecord',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
