# Generated by Django 6.0.3 on 2026-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_vatrecord_transaction_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vatrecord',
            old_name='date',
            new_name='filing_deadline',
        ),
        migrations.RemoveField(
            model_name='vatrecord',
            name='period',
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
