# Generated by Django 6.0.3 on 2026-05-14 04:19

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_rename_date_vatrecord_filing_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentServiceRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('biz', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(default='Paid', max_length=50)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
                ('draw_date', models.DateField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prize', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('claim_status', models.CharField(blank=True, max_length=50, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=100, null=True)),
                ('business', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DojoSettlement',
        ),
    ]
