# Generated by Django 6.0.3 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_paymentservicerecord_delete_dojosettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='reminder_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='reminder_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='vatrecord',
            name='reminder_days',
            field=models.IntegerField(default=14),
        ),
    ]
