# Generated by Django 6.0.5 on 2026-05-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='access',
            field=models.TextField(default='All'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
