# Generated by Django 6.0.5 on 2026-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffprofile_access_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='permissions',
            field=models.TextField(default='{}'),
        ),
    ]
