# Generated by Django 6.0.5 on 2026-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='assigned_business',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
