# Generated by Django 6.0.5 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_staffprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
