# Generated by Django 6.0.5 on 2026-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_staffprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
