# Generated by Django 6.0.4 on 2026-05-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staffprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='settings',
            field=models.TextField(default='{"disableVoiceAnnouncement": false}'),
        ),
    ]
