# Generated by Django 6.0.5 on 2026-05-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('assigned_person', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=100)),
                ('status', models.CharField(default='Operational', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(max_length=50)),
                ('technician', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.asset')),
            ],
        ),
    ]
