# Generated by Django 6.0.5 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertylicence_wastecollection_alter_asset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylicence',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='property/licences/'),
        ),
    ]
