# Generated by Django 6.0.5 on 2026-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertylicence_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertylicence',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
