# Generated by Django 6.0.3 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_asset_business_asset_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylicence',
            name='reminder_days',
            field=models.IntegerField(default=30),
        ),
    ]
