# Generated by Django 6.0.3 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertylicence_reminder_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastecollection',
            name='reminder_days',
            field=models.IntegerField(default=7),
        ),
    ]
