# Generated by Django 6.0.5 on 2026-05-06 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('business', models.CharField(max_length=255)),
                ('mot_date', models.DateField()),
                ('insurance_date', models.DateField()),
                ('road_tax_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('service_date', models.DateField()),
                ('area', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
