# Generated by Django 6.0.5 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_delivery_id_alter_parcelpartner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ins_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mot_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/mot/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/roadtax/'),
        ),
    ]
