# Generated by Django 6.0.5 on 2026-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_ins_doc_vehicle_mot_doc_vehicle_tax_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcelpartner',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcelpartner',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcelpartner',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='road_tax_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
