# Generated by Django 6.0.5 on 2026-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_delivery_business_delivery_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='reminder_before',
            field=models.IntegerField(default=30),
        ),
    ]
