# Generated by Django 6.0.5 on 2026-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_reminder_before'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='reminder_before',
            new_name='ins_reminder',
        ),
        migrations.AddField(
            model_name='parcelpartner',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mot_reminder',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_reminder',
            field=models.IntegerField(default=30),
        ),
    ]
