# Generated by Django 6.0.5 on 2026-05-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_rename_reminder_before_vehicle_ins_reminder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='ins_reminder',
            new_name='reminder_before',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_reminder',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_reminder',
        ),
    ]
