# Generated by Django 6.0.4 on 2026-05-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_rename_ins_reminder_vehicle_reminder_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
