# Generated by Django 6.0.4 on 2026-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='other_doc',
            field=models.FileField(blank=True, null=True, upload_to='fleet/other/'),
        ),
    ]
