# Generated by Django 6.0.4 on 2026-05-14 05:23

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_vehicle_other_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('business', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
