# Generated by Django 6.0.3 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='reminder_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='parcelpartner',
            name='reminder_days',
            field=models.IntegerField(default=7),
        ),
    ]
