# Generated by Django 6.0.4 on 2026-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_purchaseorder_business_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
