# Generated by Django 6.0.3 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_address_supplier_notes_supplier_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='reminder_days',
            field=models.IntegerField(default=3),
        ),
    ]
