# Generated by Django 6.0.5 on 2026-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('document_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
