# Generated by Django 6.0.5 on 2026-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_legaldocument_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='document_url',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='legal/documents/'),
        ),
    ]
