# Generated by Django 6.0.5 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_remove_legaldocument_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
