# Generated by Django 6.0.4 on 2026-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_legaldocument_business_legaldocument_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
