# Generated by Django 6.0.3 on 2026-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_legaldocument_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='reminder_days',
            field=models.IntegerField(default=7),
        ),
    ]
