# Generated by Django 6.0.5 on 2026-05-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hq_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crn', models.CharField(max_length=8, unique=True)),
                ('manager', models.CharField(max_length=255)),
                ('sic_code', models.CharField(blank=True, max_length=20, null=True)),
                ('filing_due', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
