# Generated by Django 6.0.5 on 2026-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businessentity_id_alter_companystructure_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='balance_sheet',
            field=models.FileField(blank=True, null=True, upload_to='business/balance_sheets/'),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='pl_statement',
            field=models.FileField(blank=True, null=True, upload_to='business/pl_statements/'),
        ),
    ]
