# Generated by Django 6.0.5 on 2026-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_companystructure_balance_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
