# Generated by Django 6.0.4 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_businessentity_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessentity',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/'),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='currency',
            field=models.CharField(default='GBP', max_length=10),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='businessentity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
