# Generated by Django 6.0.4 on 2026-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessentity_business_logo_businessentity_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
