# Generated by Django 6.0.4 on 2026-05-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_companystructure_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='house_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
