# Generated by Django 6.0.3 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_companystructure_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystructure',
            name='confirmation_statement_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companystructure',
            name='reminder_days',
            field=models.IntegerField(default=30),
        ),
    ]
